#!/bin/bash
set -e

if command -v terraform > /dev/null; then
  terraform fmt -check -recursive

  PROJECTS=(dx/dx-cluster dx/mimir-main-cluster dx/mimir-internal-cluster)
  for project in ${PROJECTS[@]}; do
    pushd $project
      terraform init > /dev/null
      terraform validate
    popd
  done
else
  echo warn: terraform is not available. >&2
  exit 0
fi
