#!/bin/bash
set -e

if command -v terraform > /dev/null; then
  if [[ "$BYPASS_PRE_COMMIT" = "true" ]]; then
    echo "info: pre-commit is bypassed." >&2
    exit 0
  fi

  terraform fmt -check -recursive

  PROJECTS=(dx/dx-cluster dx/mimir-main-cluster dx/mimir-internal-cluster)
  for project in ${PROJECTS[@]}; do
    pushd $project
      terraform init > /dev/null
      terraform validate
    popd
  done
else
  echo warn: terraform is not available. >&2
  exit 0
fi
